let num1: number = 5;
let num2: number = 3;
let num3: number;
num3 = num1 + num2;
console.log("Phép cộng:", num3);
num3 = num1 - num2;
console.log("Phép trừ:", num3);
num3 = num1 * num2;
console.log("Phép nhân:", num3);
num3 = num1 / num2;
console.log("Phép chia:", num3);
num1 = "Hello" as any;
console.log("num1:", num1);
num2 = false as any;
console.log("num2:", num2);
num3 = num1 + num2;
console.log("Phép cộng sau thay đổi:", num3);
num3 = num1 - num2;
console.log("Phép trừ sau thay đổi:", num3);
num3 = num1 * num2;
console.log("Phép nhân sau thay đổi:", num3);
num3 = num1 / num2;
console.log("Phép chia sau thay đổi:", num3);